<?php

/**
 * @file
 * Allows administrators to add previous/next pagers to any node type.
 */


/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function flippy_theme() {
  return array(
    'flippy' => array(
      'variables' => array(
        'list' => array(),
      ),
      'template' => 'flippy',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flippy_form_node_type_form_alter(&$form, $form_state) {
  if (isset($form['type'])) {
    $form['flippy'] = array(
      '#type' => 'fieldset',
      '#title' => t('Flippy settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['flippy']['flippy'] = array(
      '#type' => 'checkbox',
      '#title' => t('Build a pager for this content type'),
      '#default_value' => variable_get('flippy_' . $form['#node_type']->type, FALSE),
    );
    $form['flippy']['flippy_head'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add semantic previous and next links to the document HEAD'),
      '#default_value' => variable_get('flippy_head_' . $form['#node_type']->type, FALSE),
      '#states' => array(
        'visible' => array(   // action to take.
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
  }
}

/**
 * Implements hook_field_info_extra_fields().
 */

function flippy_field_extra_fields() {
  $extra = array();
  foreach (node_type_get_names() as $type => $name) {
    if (variable_get('flippy_'. $type, NULL)) {
      $extra['node'][$type] = array(
        'display' => array(
          'flippy_pager' => array(
            'label' => t('Pager'), 
            'description' => t('Flippy module content pager.'), 
            'weight' => 5,
          ), 
        ),
      );
    }
  }
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function flippy_node_view($node, $view_mode = 'full') {
  if (variable_get('flippy_'. $node->type, NULL)) {
    $node->content['flippy_pager'] = array(
      '#theme' => 'flippy',
      '#list' => flippy_build_list($node),
    );
    
    if (node_is_page($node) && variable_get('flippy_head_'. $node->type, NULL)) {
      $links = flippy_build_list($node);
      if (!empty($links['prev'])) {
        drupal_add_html_head_link(array(
          'rel' => 'prev',
          'href' => url('node/' . $links['prev']),
        ));
      }
      if (!empty($links['next'])) {
        drupal_add_html_head_link(array(
          'rel' => 'next',
          'href' => url('node/' . $links['next']),
        ));
      }
    }
  }
}

function flippy_preprocess_node($vars) {
  $node = $vars['node'];
  if (node_is_page($node) && ($pager = variable_get('flippy_'. $node->type, NULL))) {
    $vars['flippy']['ids'] = flippy_build_list($node);
  }
}

function flippy_build_list($node) {
  $master_list = &drupal_static(__FUNCTION__);
  if (!isset($master_list)) {
    $master_list = array();
  }
  if (!isset($master_list[$node->nid])) {
    // Create a starting-point query object
    $query = db_select('node')
      ->fields('node', array('nid'))
      ->condition('nid', $node->nid, '!=')
      ->condition('status', 1)
      ->condition('type', $node->type, '=')
      ->range(0, 1);

    $list['current'] = $node->nid;

    $prev = clone $query;
    $list['prev'] = $prev
      ->condition('created', $node->created, '<=')
      ->orderBy('created', 'DESC')
      ->execute()->fetchField();

    $next = clone $query;
    $list['next'] = $next
      ->condition('created', $node->created, '>=')
      ->orderBy('created', 'ASC')
      ->execute()->fetchField();
 
    $master_list[$node->nid] = $list;
  }
  return $master_list[$node->nid];
}

function _flippy_nids_to_nodes(array $pager) {
  $nids = array_values($pager);
  $nodes = node_load_multiple($nids);
  foreach ($pager as $key => $nid) {
    $pager[$key] = $nodes[$nid];
  }
  return $pager;
}

function template_preprocess_flippy(&$vars) {
  drupal_add_css(drupal_get_path('module', 'flippy') . '/flippy.css');

  if ($nav = $vars['list']) {
    
    $vars['previous_link'] =  empty($nav['prev']) ? '' : l('< ' . t('previous'), 'node/' . $nav['prev']);
    $vars['next_link'] =  empty($nav['next']) ? '' : l(t('next') . ' >', 'node/' . $nav['next']);
    
  }
}